name: Tests

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
jobs:
  benchmark:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock') }}-${{ github.sha }}-tests
        restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock') }}-${{ github.sha }}
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock') }}-
            ${{ runner.os }}-cargo-
  
    - name: Install dependencies
      run: |
        sudo apt-get install g++ linux-libc-dev libclang-dev unzip libjemalloc-dev make -y
        sudo apt-get install -y time

    - name: Build Debug
      run: cargo build --verbose

    - name: Run unit tests
      run:
        RUSTFLAGS="-Awarnings" cargo test --workspace
      continue-on-error: true